### PR TITLE
Allow a TLS option

### PR DESCRIPTION
**Pull request by joaojeronimo**
Hi, I'm running a setup that encrypts traffic with TLS, so I have a "TLS proxy" on the same machine as my server that "unwraps the TLS" so that a client connects to it with TLS, then it unwraps and forwards all communications to the database. That proxy looks a bit like this:
```js
var tls = require('tls');
var net = require('net');
var tlsOpts = {}; // public certificate and private key
tls.createServer(tlsOpts, function (socket) {
    var conn = net.createConnection('localhost', 28015);
    socket.pipe(conn).pipe(socket);
}).listen(29015);
```

So on the client's end I had to create a normal TCP server that would forward all it's connections to a TLS client, that would in turn connect to that TLS server above. I would look like this:

```js
var tls = require('tls');
var net = require('net');
net.createServer(function (socket) {
  var encryptedConn = tls.connect(29015);
  socket.pipe(encryptedConn).pipe(socket);
}).listen(30015);
```

So now if I point my regular rethinkdb client to localhost:30015, all it's connections would be TLS wrapped to the server, which is a good thing. But it's messy, hence this patch that I hope you like, which allows you tu pass a `tls` option when constructing the rethinkdbdash client, like this:

```js
var r = require('rethinkdbdash')({
  host: 'localhost',
  port: '29015',
  tls: true
});
```

And now there would be no need for the "tls wrapper" on the client's end. The `tls` option may be an object that will directly be passed to the options of `tls.connect()`, so if you are using a self-signed certificate and need to pass a private CA for instance, this would work:

```js
var fs = require('fs');
var r = require('rethinkdbdash')({
  host: 'localhost',
  port: '29015',
  tls: {
    ca: [fs.readFileSync('./certs/my-private-root-ca.crt.pem')]
  }
});
```

I also added a test. Is everything ok ? Is this patch useful ?

PS: one of the tests (the one who passes an options object to the tls parameter) can only be ran on localhost, because the self signed certificate is only good for localhost. I didn't create another one specific for werker because I'm not sure if it will be the same IP address forever, probably not. Another idea would be to generate the self signed certificates at the begining of the tests for the WERCKER_RETHINKDB_HOST variable and delete it at the end but it seemed an overkill.

### CODE REVIEW

**Comment by neumino** [comment]
Hello @joaojeronimo, thanks for the pull request!

I'm not sure this is something that should go in the driver itself. It seems more like something that should sit on top of the driver/server. What you mentioned (setting up two servers) seems like the way to go. It seems weird to me to have the driver connect on something that is not a RethinkDB server (though your use case is totally legit).

It also raises the problem on how to handle errors - certificate errors, connection between the "TLS server" and RethinkDB hanging.

Is there a reason why you need to directly connect the driver to the "TLS" besides the overhead of running a local server?
I also saw that you commented on https://github.com/rethinkdb/rethinkdb/issues/3158, which should be the way to go (once it's implemented). My guess is that since 2.0 is coming in a few weeks, this is the kind of thing that will be rolled out pretty soon (I may be wrong though).

**Comment by joaojeronimo** [comment]
My only argument is less moving parts is always best, and especially on the client side it's unacceptable to have to manage a TLS proxy or an SSH tunnel.

As for certificate errors, nodejs' default behavior is to throw, in my opinion I think it's acceptable. Connection between the "TLS server" and rethinkdb hanging is out of scope here, I think this patch allows a "bring your own TLS proxy on the server" kind of thing where you could choose to have stunnel, stud, about 3 lines of javascript code or whatever proxy on the server and I have no silver bullet to tackle the errors between whatever tls proxy someone decides to run and rethinkdb.

I also did this hoping that rethinkdb would come out with a TLS server (awesome news if it will be on 2.0 and it's coming in a few weeks), then this would work just as well. I think the code in this patch is as simple as it can get for a client making TLS connections and not at all limiting in any terms.

**Comment by joaojeronimo** [comment]
Hey  @neumino, I'm not sure what's going on but it seems the other clients are implementing SSL: https://github.com/rethinkdb/rethinkdb/pull/4075, https://github.com/rethinkdb/rethinkdb/pull/4076 and https://github.com/rethinkdb/rethinkdb/pull/4080. I'm not sure what's intended, is this patch still ok ?

**Comment by neumino** [comment]
Thanks @joaojeronimo -- I'll follow up there.

**Comment by neumino** [comment]
Ok, that's merged in the branch `raftTls` and should be released in 2.1.

**Pull request merged**
