### PR TITLE
Syncing cursor.next() error message with rethinkdb.

### LINKED ISSUE #137: cursor.next() error message is not synced with rethinkdb.
The error messages thrown when there are no more rows to fetch are different for rethinkdb and rethinkdbdash.

Rethinkdb

```javascript
No more rows in the cursor.
```

Rethinkdbdash

```javascript
No more rows in the Cursor. //Note the capital C.
```

### PR DESCRIPTION
**Pull request by kulbirsaini**
Fixes #137

### CODE REVIEW

**Comment by neumino** [comment]
Can you just fix error message with a if statement for `Cursor`. Your change make `cursor.toString()` to return `[object cursor]`.

**Comment by kulbirsaini** [comment]
I based my commit on Cursor initialization from [here](https://github.com/neumino/rethinkdbdash/blob/master/lib/connection.js#L252) and [here](https://github.com/neumino/rethinkdbdash/blob/master/lib/connection.js#L267). Those cursors will return `[object cursor]` as well.

**Comment by neumino** [comment]
Sorry I mean that `cursor.toString()` should return `[object Cursor]` and not `[object cursor]`

**Comment by kulbirsaini** [comment]
Thanks for clearing that. Updated.

**Comment by neumino** [comment]
Sorry, I'm very bad at explaining myself tonight. Can you just change these two lines by special casing when `this._type === "Cursor"`?
https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L57
https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L166

The typeResult is basically the "Class" of the object and should have a capital. I'm fine cheating a little for the "no more rows" error if it get the driver closer to RethinkDB.

Note that this will be released in 2.2, not 2.1.x since it's a breaking change.

**Comment by kulbirsaini** [comment]
I am sorry I totally read that wrong. I hope I got it right this time.

**Comment by neumino** [comment]
Thanks, looks good to me

**Comment by marshall007** [comment]
Looking over at [`drivers/javascript/cursor.coffee`](https://github.com/rethinkdb/rethinkdb/blob/e6d2f1b2a87f82f1cae9ad0495f1f51fc44eba22/drivers/javascript/cursor.coffee) it appears that there are several other inconsistencies between error messages.

Perhaps it would be worth opening up an issue in [rethinkdb/rethinkdb](https://github.com/rethinkdb/rethinkdb) to discuss and make them aware? I'd actually prefer to see the official driver update to use capitalization (ex. `No more rows in the Cursor.`) since the messages are referring to class types.

**Comment by marshall007** [comment]
Also note the official driver isn't even internally consistent with these messages. For example on [this line](https://github.com/rethinkdb/rethinkdb/blob/e6d2f1b2a87f82f1cae9ad0495f1f51fc44eba22/drivers/javascript/cursor.coffee#L275) `EventEmitter` is indeed capitalized, but `cursor` is not.

**Comment by neumino** [comment]
Hum, so error messages were never in synced with the official driver. For example:
- rethinkdbdash checks arity error while the official driver doesn't.
- rethinkdbdash prints backtraces in a different way (better I think)
- Some subtle edge cases produce different errors (like if a connection is abruptly ended by a router)

Basically whether we capitalize things in rethinkdbdash can be summed up as `cursor = new Cursor()`. For the "no more rows" error it make sense to sync with the official driver since it makes swapping drivers easier.

**Pull request merged**
