### PR TITLE
Use --harmony instead of --harmony-generators for Node v4.0

### PR DESCRIPTION
**Pull request by kulbirsaini**

### CODE REVIEW

**Comment by neumino** [comment]
Thanks, I'll finish updating the wercker box tonight and merge your PR then. I have a few issues building node 4.1 there and I should probably revert to just downloading a binary since rethinkdbdash doesn't use a fancy version of node anymore.

Thanks again for the PR!

**Comment by kulbirsaini** [comment]
We also need to raise the mocha timeout. Last build for my other PR failed because of timeout.

**Comment by kudos** [comment]
You don't need any flag for generators on Node v4. Run this to see the features currently behind the harmony flag

```
$ node --v8-options | grep "in progress"
```

**Comment by kulbirsaini** [comment]
@kudos it's for backward compatibility with node v0.12 or less.

**Pull request merged**
