### PR TITLE
Call callback on closed cursors

### PR DESCRIPTION
**Pull request by Marsup**
Found this bug while reinstalling my deps from a previous patch version of rethinkdbdash.

### CODE REVIEW

**Comment by Marsup** [comment]
@neumino any chance you have a look at this ?

**Comment by neumino** [comment]
@Marsup sorry I missed this PR, looks good to me.

**Comment by neumino** [comment]
Out in 2.3.28

**Comment by Marsup** [comment]
Thanks a lot !

**Pull request merged**
