### PR TITLE
RFC for #211 - .msg missing in error object

### LINKED ISSUE #211: msg absent on error
With the rethinkdb driver I get an error object with `msg, message, frames, and name`, but with rethinkdbdash, `msg` is absent.
```javascript
function *() {
  try {
    yield r.error('My custom error.')
  } catch(ex) {
    this.type = 'json'
    this.body = { error: ex }
  }
}
```
I want to get the `msg` from `r.error`, but doen't exists in the catched `ex`.
I did a repo for reproduction here: [NicolasParada/rethinkdbdash-msg-absent](https://github.com/NicolasParada/rethinkdbdash-msg-absent)

### PR DESCRIPTION
**Pull request by frankleng**
fixes #211
based on official driver https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/errors.coffee

### CODE REVIEW

**Comment by neumino** [comment]
I don't remember why I wasn't a big fan of #211, but I think at that time there wasn't `r.error`, so you couldn't throw your own error.

That sounds reasonable. Should we name it something else than `msg` though? Do we care about being consistent with the official driver or should we pick a better name?

**Comment by frankleng** [comment]
@neumino
Was wondering the same thing. Leaning toward being consistent with official driver to minimize friction when migrating between drivers.

**Comment by neumino** [comment]
Pushed in 2.3.8

**Comment by neumino** [comment]
Thanks @frankleng for the PR :)

**Comment by frankleng** [comment]
@neumino thanks for this awesome driver!

**Pull request merged**
