### PR TITLE
Emit errors from pool, through pool master, so they can be caught

### PR DESCRIPTION
**Pull request by ewnavilae**
I made this change to allow me to handle a Wrong Password error thrown by rethink DB.
This is my use case: 

```javascript
const r = _r( {
  host: "192.168.1.89",
  user: "admin",
  password: process.env.RETHINK_PASSWORD,
  db: "deployments",
  silent: true,
} )

r.getPoolMaster()
  .on( "error", ( error ) => (
    error.message.indexOf( "Wrong password" ) > -1 ? process.exit(1) : console.error( error.message )
  ) )
```

### CODE REVIEW

**Comment by neumino** [comment]
You can just listen to the `log` event instead of propagating things through `error`. There's no need to propagate this `error` event.

**Comment by ewnavilae** [comment]
If I remember correctly I tried that and it didn't behave as I expected, I think a default message was being logged (generic error with stacktrace about wrong password) and my log event didn't get triggered. If I have chance I'll test it again and update this.

**Comment by JohnyDays** [comment]
If this isn't propagated, node throws an Unhandled Rejection error, so it actually isn't possible to catch it or log it (node crashes).

**Comment by julienvincent** [comment]
I would also like to see this implemented.

**Comment by neumino** [comment]
This is already implemented. If the `silent` option and the `log` events are not enough, please open an issue with the full use case and why these two features are not enough.

**Pull request closed without merging**
